---
# Ansible role
#
# Instalace fusiondirectory

- name: Přidá GPG klíč FusionDirectory repozitáře
  apt_key:
    data: "{{ lookup('file', 'fusion.key') }}"
    id: '0xD744D55EACDA69FF'

- name: Přidá FusionDirectory repozitáře
  apt_repository:
    repo: '{{ item.repo }}'
    filename: '{{ item.filename }}'
    state: present
  loop: '{{ fusiondirectory.apt.repos }}'

- name: Instalace FusionDirectory
  apt:
    name:
      - 'fusiondirectory'
      - 'fusiondirectory-schema'
  notify: import core schemas

- name: Instalace FusionDirectory plugin
  apt:
    name: '{{ fusiondirectory.plugins | default([]) }}'
  notify: import plugin schemas

- meta: flush_handlers

- name: Nastavení FusionDirectory indexů
  ldap_attr:
    dn: 'olcDatabase={1}mdb,cn=config'
    name: 'olcDbIndex'
    values: '{{ item }}'
    state: present
  loop: '{{ fusiondirectory.indices | default([]) }}'
  tags: fd-index

- name: Instalace konfiguračního souboru
  template:
    dest: '/etc/fusiondirectory/fusiondirectory.conf'
    src: 'fusiondirectory.conf.j2'
    owner: 'root'
    group: 'www-data'
    mode: '0640'

...
